services:
  # Base de données MySQL (Privée)
  - type: pvt
    name: clinique-mysql
    env: docker
    plan: free
    dockerContext: .
    dockerfilePath: docker/mysql.Dockerfile
    envVars:
      - key: MYSQL_ROOT_PASSWORD
        value: root
      - key: MYSQL_DATABASE
        value: clinique_db

  # Backend Spring Boot
  - type: web
    name: clinique-backend
    env: docker
    repo: https://github.com/Khaoulachaouaty/CliniqueSpringBoot
    rootDir: Clinique
    plan: free
    envVars:
      - key: MYSQL_HOST
        value: clinique-mysql
      - key: MYSQL_USER
        value: root
      - key: MYSQL_PASSWORD
        value: root

  # Frontend Angular
  - type: web
    name: clinique-frontend
    env: docker
    repo: https://github.com/Khaoulachaouaty/CliniqueSpringBoot
    rootDir: clinique_frontend
    plan: free
    envVars:
      - key: BACKEND_URL
        value: https://clinique-backend.onrender.com
