services:
  # Backend Spring Boot
  - type: web
    name: clinique-backend
    env: docker
    repo: https://github.com/Khaoulachaouaty/CliniqueSpringBoot
    rootDir: Clinique
    plan: free
    envVars:
      - key: MYSQL_HOST
        fromDatabase:
          name: clinique-db
          property: host
      - key: MYSQL_USER
        value: root
      - key: MYSQL_PASSWORD
        value: root

  # Frontend Angular
  - type: web
    name: clinique-frontend
    env: docker
    repo: https://github.com/Khaoulachaouaty/CliniqueSpringBoot
    rootDir: clinique_frontend
    plan: free
    envVars:
      - key: BACKEND_URL
        value: https://clinique-backend.onrender.com

databases:
  - name: clinique-db
    databaseName: clinique_DB
    user: root
    plan: free
