apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'spring-boot'
        metrics_path: '/clinique/actuator/prometheus'
        static_configs:
          - targets: ['backend.clinique.svc.cluster.local:8082']