apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: clinique
type: Opaque
data:
  # echo -n "root" | base64
  root-password: cm9vdA==
  # echo -n "clinique_DB" | base64
  database: Y2xpbmlxdWVfREI=
  # echo -n "root" | base64
  username: cm9vdA==