spring.application.name=clinique-2
spring.datasource.url=jdbc:mysql://localhost:3306/clinique_DB?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true
server.servlet.context-path=/clinique
server.port=8081
